/**
 * Browser-local model metadata used to boot the UI without calling the API.
 *
 * This file is the typed source of truth for browser-native model metadata.
 * Build it with `npm run build` to regenerate `js/model-data.js`.
 */

import type { ModelDataPayload } from "./simulation-contracts.js";

export const ModelData: ModelDataPayload = {
  constantDefaults: {
    ahl70: 1.5,
    alai1: 2,
    alai2: 2,
    ali: 900000000.0,
    alic1: 14,
    alic2: 14,
    alln: 1000,
    alsc1: 20,
    alsc2: 20,
    amti: 1,
    dcfsn: 3.8,
    fcest: 4000,
    fioac1: 0.43,
    fioac2: 0.43,
    fipm: 0.001,
    frpm: 0.02,
    fspd: 2,
    hsid: 20,
    ici: 210000000000.0,
    icor1: 3,
    icor2: 3,
    ieat: 3,
    iet: 4000,
    ilf: 600,
    imef: 0.1,
    imti: 10,
    io70: 790000000000.0,
    iopcd: 400,
    len: 28,
    lferti: 600,
    lfh: 0.7,
    lfpf: 0.75,
    lpd: 20,
    lufdt: 2,
    lyf1: 1,
    lyf2: 1,
    mtfn: 12,
    nri: 1000000000000.0,
    nruf1: 1,
    nruf2: 1,
    p1i: 650000000.0,
    p2i: 700000000.0,
    p3i: 190000000.0,
    p4i: 60000000.0,
    pali: 2300000000.0,
    palt: 3200000000.0,
    pet: 4000,
    pl: 0.1,
    ppgf1: 1,
    ppgf2: 1,
    ppgf21: 1,
    ppol70: 136000000.0,
    ppoli: 25000000.0,
    pptd1: 20,
    pptd2: 20,
    rlt: 30,
    sad: 20,
    sci: 144000000000.0,
    scor1: 1,
    scor2: 1,
    sd: 0.07,
    sfpc: 230,
    uildt: 10,
    uili: 8200000.0,
    zpgt: 4000,
  },

  constantMeta: {
    ahl70: { full_name: "Assimilation half-life in 1970", sector: "Pollution", unit: "years" },
    alai1: { full_name: "Avg lifetime agricultural input 1", sector: "Agriculture", unit: "years" },
    alai2: { full_name: "Avg lifetime agricultural input 2", sector: "Agriculture", unit: "years" },
    ali: { full_name: "Initial arable land", sector: "Agriculture", unit: "ha" },
    alic1: { full_name: "Avg lifetime industrial capital 1", sector: "Capital", unit: "years" },
    alic2: { full_name: "Avg lifetime industrial capital 2", sector: "Capital", unit: "years" },
    alln: { full_name: "Average life of land normal", sector: "Agriculture", unit: "years" },
    alsc1: { full_name: "Avg lifetime service capital 1", sector: "Capital", unit: "years" },
    alsc2: { full_name: "Avg lifetime service capital 2", sector: "Capital", unit: "years" },
    amti: { full_name: "Agricultural material toxicity index", sector: "Pollution", unit: "-" },
    dcfsn: { full_name: "Desired completed family size normal", sector: "Population", unit: "children" },
    fcest: { full_name: "Fertility control effectiveness set time", sector: "Population", unit: "year" },
    fioac1: { full_name: "Fraction industrial output for consumption 1", sector: "Capital", unit: "-" },
    fioac2: { full_name: "Fraction industrial output for consumption 2", sector: "Capital", unit: "-" },
    fipm: { full_name: "Fraction industrial pollution manageable", sector: "Pollution", unit: "-" },
    frpm: { full_name: "Fraction resources as pollution material", sector: "Pollution", unit: "-" },
    fspd: { full_name: "Food shortage perception delay", sector: "Agriculture", unit: "years" },
    hsid: { full_name: "Health services impact delay", sector: "Population", unit: "years" },
    ici: { full_name: "Initial industrial capital", sector: "Capital", unit: "$" },
    icor1: { full_name: "Industrial capital-output ratio 1", sector: "Capital", unit: "years" },
    icor2: { full_name: "Industrial capital-output ratio 2", sector: "Capital", unit: "years" },
    ieat: { full_name: "Income expectation averaging time", sector: "Population", unit: "years" },
    iet: { full_name: "Industrial equilibrium time", sector: "Capital", unit: "year" },
    ilf: { full_name: "Inherent land fertility", sector: "Agriculture", unit: "kg/ha/yr" },
    imef: { full_name: "Industrial material emission factor", sector: "Pollution", unit: "-" },
    imti: { full_name: "Industrial material toxicity index", sector: "Pollution", unit: "-" },
    io70: { full_name: "Industrial output in 1970", sector: "Agriculture", unit: "$/yr" },
    iopcd: { full_name: "Industrial output per capita desired", sector: "Capital", unit: "$/person/yr" },
    len: { full_name: "Life expectancy normal", sector: "Population", unit: "years" },
    lferti: { full_name: "Initial land fertility", sector: "Agriculture", unit: "kg/ha/yr" },
    lfh: { full_name: "Land fraction harvested", sector: "Agriculture", unit: "-" },
    lfpf: { full_name: "Labor force participation fraction", sector: "Capital", unit: "-" },
    lpd: { full_name: "Lifetime perception delay", sector: "Population", unit: "years" },
    lufdt: { full_name: "Labor utilization fraction delay time", sector: "Capital", unit: "years" },
    lyf1: { full_name: "Land yield factor 1", sector: "Agriculture", unit: "-" },
    lyf2: { full_name: "Land yield factor 2", sector: "Agriculture", unit: "-" },
    mtfn: { full_name: "Maximum total fertility normal", sector: "Population", unit: "children" },
    nri: { full_name: "Initial nonrenewable resources", sector: "Resources", unit: "resource units" },
    nruf1: { full_name: "Nonrenewable resource usage factor 1", sector: "Resources", unit: "-" },
    nruf2: { full_name: "Nonrenewable resource usage factor 2", sector: "Resources", unit: "-" },
    p1i: { full_name: "Initial population 0-14", sector: "Population", unit: "people" },
    p2i: { full_name: "Initial population 15-44", sector: "Population", unit: "people" },
    p3i: { full_name: "Initial population 45-64", sector: "Population", unit: "people" },
    p4i: { full_name: "Initial population 65+", sector: "Population", unit: "people" },
    pali: { full_name: "Initial potentially arable land", sector: "Agriculture", unit: "ha" },
    palt: { full_name: "Potentially arable land total", sector: "Agriculture", unit: "ha" },
    pet: { full_name: "Population equilibrium time", sector: "Population", unit: "year" },
    pl: { full_name: "Processing loss", sector: "Agriculture", unit: "-" },
    ppgf1: { full_name: "Persistent pollution gen factor 1", sector: "Pollution", unit: "-" },
    ppgf2: { full_name: "Persistent pollution gen factor 2", sector: "Pollution", unit: "-" },
    ppgf21: { full_name: "Persistent pollution gen factor 2 (post-policy)", sector: "Pollution", unit: "-" },
    ppol70: { full_name: "Pollution level in 1970", sector: "Pollution", unit: "pollution units" },
    ppoli: { full_name: "Initial persistent pollution", sector: "Pollution", unit: "pollution units" },
    pptd1: { full_name: "Pollution transmission delay 1", sector: "Pollution", unit: "years" },
    pptd2: { full_name: "Pollution transmission delay 2", sector: "Pollution", unit: "years" },
    rlt: { full_name: "Reproductive lifetime", sector: "Population", unit: "years" },
    sad: { full_name: "Social adjustment delay", sector: "Population", unit: "years" },
    sci: { full_name: "Initial service capital", sector: "Capital", unit: "$" },
    scor1: { full_name: "Service capital-output ratio 1", sector: "Capital", unit: "years" },
    scor2: { full_name: "Service capital-output ratio 2", sector: "Capital", unit: "years" },
    sd: { full_name: "Social discount", sector: "Agriculture", unit: "-" },
    sfpc: { full_name: "Subsistence food per capita", sector: "Agriculture", unit: "kg/yr" },
    uildt: { full_name: "Urban-industrial land development time", sector: "Agriculture", unit: "years" },
    uili: { full_name: "Initial urban-industrial land", sector: "Agriculture", unit: "ha" },
    zpgt: { full_name: "Zero population growth time", sector: "Population", unit: "year" },
  },

  variableMeta: {
    aiph: { full_name: "Agricultural inputs per hectare", sector: "Agriculture", unit: "$/ha/yr" },
    al: { full_name: "Arable land", sector: "Agriculture", unit: "ha" },
    cbr: { full_name: "Crude birth rate", sector: "Population", unit: "births/1000/yr" },
    cdr: { full_name: "Crude death rate", sector: "Population", unit: "deaths/1000/yr" },
    f: { full_name: "Total food production", sector: "Agriculture", unit: "kg/yr" },
    fcaor: { full_name: "Fraction capital allocated to obtaining resources", sector: "Resources", unit: "-" },
    fioaa: { full_name: "Fraction industrial output for agriculture", sector: "Capital", unit: "-" },
    fpc: { full_name: "Food per capita", sector: "Agriculture", unit: "kg/person/yr" },
    io: { full_name: "Industrial output", sector: "Capital", unit: "$/yr" },
    iopc: { full_name: "Industrial output per capita", sector: "Capital", unit: "$/person/yr" },
    le: { full_name: "Life expectancy", sector: "Population", unit: "years" },
    ly: { full_name: "Land yield", sector: "Agriculture", unit: "kg/ha/yr" },
    nr: { full_name: "Nonrenewable resources remaining", sector: "Resources", unit: "resource units" },
    nrfr: { full_name: "Nonrenewable resource fraction remaining", sector: "Resources", unit: "-" },
    pop: { full_name: "Total population", sector: "Population", unit: "people" },
    ppol: { full_name: "Persistent pollution", sector: "Pollution", unit: "pollution units" },
    ppolx: { full_name: "Pollution index", sector: "Pollution", unit: "-" },
    so: { full_name: "Service output", sector: "Capital", unit: "$/yr" },
    sopc: { full_name: "Service output per capita", sector: "Capital", unit: "$/person/yr" },
    tai: { full_name: "Total agricultural investment", sector: "Agriculture", unit: "$/yr" },
  },

  defaultVariables: [
    "pop",
    "nr",
    "nrfr",
    "io",
    "iopc",
    "fpc",
    "f",
    "so",
    "sopc",
    "ppolx",
    "ppol",
    "al",
    "ly",
    "le",
    "cbr",
    "cdr",
    "fioaa",
    "fcaor",
    "tai",
    "aiph",
  ],

  presets: [
    {
      name: "comprehensive-policy",
      description: "Combined technology, population, and agriculture improvements.",
      constants: {
        alai2: 4.0,
        dcfsn: 2.0,
        icor2: 2.0,
        imef: 0.05,
        lyf2: 2.0,
        nruf2: 0.5,
        pet: 2000,
        ppgf2: 0.5,
        zpgt: 2000,
      },
    },
    {
      name: "doubled-resources",
      description: "What if the initial nonrenewable resource base were twice as large?",
      constants: {
        nri: 2000000000000.0,
      },
    },
    {
      name: "optimistic-technology",
      description: "What if technology halves pollution and doubles resource efficiency?",
      constants: {
        imef: 0.05,
        nruf2: 0.5,
        ppgf2: 0.5,
      },
    },
    {
      name: "population-stability",
      description: "What if desired family size drops and population stabilizes earlier?",
      constants: {
        dcfsn: 2.0,
        pet: 2000,
        zpgt: 2000,
      },
    },
    {
      name: "standard-run",
      description: "Business as usual — all World3 defaults with no policy changes.",
      constants: {},
    },
  ],
};
